[build]
  command = "npm ci || npm i"
  publish = "."

[functions]
  directory = "netlify/functions"
  # esbuild is the current default; we declare it explicitly.
  node_bundler = "esbuild"

# Keep function routes reachable
[[redirects]]
  from = "/.netlify/functions/*"
  to   = "/.netlify/functions/:splat"
  status = 200
